title: "Curriculum"
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
color_scheme: "light"
search_enabled: false
# logo: "/Curriculum/assets/images/EWLogo.png"
collections:
  legacy:
    output: false
